services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./docker-data/data:/data"
      - "./docker-data/music:/music:ro"
